# Generated by Django 5.1.5 on 2025-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberProperty',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_prime', models.BooleanField(null=True)),
                ('is_perfect', models.BooleanField(null=True)),
            ],
        ),
    ]
