# Generated by Django 5.1.5 on 2025-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberproperty',
            name='is_perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='numberproperty',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
