# Generated by Django 5.1.5 on 2025-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskone', '0002_alter_numberproperty_is_perfect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberproperty',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
